// Bundles the static app into a single Supabase Edge Function that serves it.
// Usage (from WFD-MONEY/): node build-edge.js > supabase/functions/money/index.ts
const fs = require('fs');
const files = {
  'index.html': 'text/html; charset=utf-8',
  'app.js': 'text/javascript; charset=utf-8',
  'logic.js': 'text/javascript; charset=utf-8',
  'sw.js': 'text/javascript; charset=utf-8',
  'styles.css': 'text/css; charset=utf-8',
  'manifest.webmanifest': 'application/manifest+json',
  'icons/icon-192.png': 'image/png',
  'icons/icon-512.png': 'image/png',
  'icons/apple-touch-icon.png': 'image/png'
};
const entries = Object.entries(files).map(([f, type]) => {
  const bin = type === 'image/png';
  const data = bin ? fs.readFileSync(f).toString('base64') : fs.readFileSync(f, 'utf8');
  return '  ' + JSON.stringify('/' + f) + ': { type: ' + JSON.stringify(type) + ', bin: ' + bin + ', data: ' + JSON.stringify(data) + ' },';
}).join('\n');

const out = [
  '// Generated by build-edge.js. Serves the WFD Money static app from one Edge Function.',
  'const FILES: Record<string, { type: string; bin: boolean; data: string }> = {',
  entries,
  '};',
  'function body(f: { bin: boolean; data: string }): Uint8Array | string {',
  '  if (!f.bin) return f.data;',
  '  const raw = atob(f.data); const out = new Uint8Array(raw.length);',
  '  for (let i = 0; i < raw.length; i++) out[i] = raw.charCodeAt(i);',
  '  return out;',
  '}',
  'Deno.serve((req: Request) => {',
  '  const url = new URL(req.url);',
  '  // path after the function name: /functions/v1/money/app.js -> /app.js',
  '  const m = url.pathname.match(/^\\/(?:functions\\/v1\\/)?money(\\/.*)?$/);',
  '  let rest = m ? (m[1] || "") : url.pathname;',
  '  if (rest === "") return Response.redirect(url.origin + url.pathname + "/" + url.search, 302);',
  '  if (rest === "/") rest = "/index.html";',
  '  const f = FILES[rest];',
  '  if (!f || req.method !== "GET") return new Response("Not found", { status: 404 });',
  '  const cache = f.bin ? "public, max-age=86400" : "no-cache";',
  '  return new Response(body(f), { headers: { "Content-Type": f.type, "Cache-Control": cache, "X-Content-Type-Options": "nosniff", "X-Frame-Options": "DENY" } });',
  '});',
  ''
].join('\n');
process.stdout.write(out);
