"""Assembly step sequence. One entry per page of the build manual.

`groups`  - member groups (from geometry.py) that get INSTALLED at this step
`objects` - extra Blender object-name substrings installed at this step
`carry`   - True if earlier steps stay visible in grey (always true except step 1)
"""
STEPS = [
 dict(n=1,  title="Find your studs",
      groups=[], objects=[], shell=True,
      tools="stud finder, pencil, 4 ft level",
      text=["Mark the centre of every stud on both walls, floor to 48 inches.",
            "Mark a level line at 37-3/4 inches on both walls. That is the underside",
            "of the deck framing and every other height comes off it.",
            "If your studs are not 16 inches on centre, that is fine. Move the bolts",
            "to land on wood. Never anchor a ledger to drywall."],
      warn="Do not skip this. Everything above hangs off these two walls."),
 dict(n=2,  title="Bolt the two wall ledgers",
      groups=["Loft / Ledgers"], objects=[],
      tools='drill, 9/16 socket, 3/8 x 4 lag screws + washers',
      extra=[(8, '3/8" x 4" lag screw + washer'), (1, 'tube construction adhesive (optional)')],
      text=["North wall ledger first, west wall ledger butts into it.",
            "Top edge of both ledgers sits on your 37-3/4 inch line.",
            "Two 3/8 x 4 lag screws into EVERY stud, staggered high and low.",
            "Pre-drill a 1/4 inch pilot so the lag does not split the ledger."],
      warn="These two boards carry the whole loft. The posts are secondary."),
 dict(n=3,  title="Stand the five posts",
      groups=["Loft / Posts"], objects=[],
      tools="post bases, level, 1/4 x 3 lag screws",
      extra=[(3, 'Simpson ABU44Z post base'), (12, '1/4" x 3" lag screw')],
      text=["Four tall posts at 80 inches: B, C, D, E.",
            "One short stub at 37-3/4 inches in the room corner: A.",
            "Post D is the diagonal corner. Turn it 45 degrees so its faces",
            "meet both rim boards square.",
            "Plumb every post in two directions before you fix the base."],
      warn="Post B and post E sit against a wall. Lag them to a stud as well."),
 dict(n=4,  title="Rim boards — only two saw settings",
      groups=["Loft / Rim"], objects=[],
      tools="miter saw, 3 inch structural screws",
      text=["Three boards close the deck: 30 inches, 42-7/16 inches, 30 inches.",
            "Set the saw to 45 degrees for the two ends that meet a wall.",
            "Set it to 22-1/2 degrees for the four ends at the diagonal corners.",
            "That is every angle cut in this entire build."],
      warn="Cut the 42-7/16 board last and measure the real gap first."),
 dict(n=5,  title="Hang the joists",
      groups=["Loft / Joists"], objects=[],
      tools="joist hangers, hanger nails, speed square",
      extra=[(3, 'Simpson LUS26 joist hanger'), (4, 'Simpson LSU26 skewable hanger'), (1, 'box hanger nails')],
      text=["Three 2x6 joists at 16 inches on centre, hung off the west ledger.",
            "J1 is square both ends and takes plain LUS26 hangers.",
            "J2 and J3 die into the diagonal rim at 45 degrees. Use the",
            "adjustable LSU26 hangers and bend them to the angle.",
            "Two short blocks behind the diagonal support the deck edge."],
      warn="Every hanger hole gets a nail. Do not toe-nail a joist."),
 dict(n=6,  title="Screw down the deck",
      groups=[], objects=["LoftDeck"],
      tools="jigsaw, chalk line, 1-5/8 inch screws",
      extra=[(1, '3/4" plywood deck, five-sided, ~22 sq ft'), (1, 'box #8 x 1-5/8" screws')],
      text=["One piece of 3/4 inch plywood, cut to the five-sided outline.",
            "Trace it off the frame you just built rather than off the drawing.",
            "Screws every 8 inches into every joist and all the way round the rim.",
            "Countersink every head. Bare feet and bare knees live up here."],
      warn="Screwed, never nailed. Nails work loose and back out."),
 dict(n=7,  title="Frame the knee wall",
      groups=["Loft / Knee wall"], objects=[],
      tools="nail gun or screws, level",
      text=["Bottom plate is pressure treated because it touches the subfloor.",
            "Studs are 34-3/4 inches. Cut one, hold it in place, confirm,",
            "then cut the rest.",
            "This wall carries nothing. It encloses the den and holds the door."],
      warn="Leave the door bay open. The next step fills it."),
 dict(n=8,  title="Frame the round door opening",
      groups=["Loft / Round door"], objects=["Round door ring"],
      tools="router + circle jig, jigsaw, 3/4 inch plywood",
      extra=[(1, '3/4" ply ring, 30" outside / 28" inside'), (1, 'router circle jig')],
      text=["Frame a SQUARE 30 x 30 inch rough opening. King studs, jack studs,",
            "a flat 2x4 header and three short cripples above it.",
            "You never cut a curved stud.",
            "Then cut four plywood quadrants with a router and circle jig and",
            "screw them into the corners of that square. They form the",
            "28 inch circle. Sand the joints until you cannot feel them."],
      warn="Dry-fit all four quadrants before you glue anything."),
 dict(n=9,  title="Skin it and set the porthole",
      groups=[], objects=["Skin "],
      tools="jigsaw, hole saw, 1-5/8 inch screws",
      extra=[(3, '3/4" ext ply skin panel'), (1, '8" acrylic porthole disc'), (1, 'clear silicone')],
      text=["Three plywood panels close the knee wall.",
            "SCREW the panel on the north face, never glue it. That panel is",
            "how an adult gets in if a small child is hurt inside.",
            "Cut the 8 inch porthole with a hole saw and bed the acrylic disc",
            "in clear silicone.",
            "Drill a pattern of 1-1/4 inch holes near the top of two panels",
            "so the den breathes."],
      warn="1-1/4 inch holes. Never 3/8 to 1 inch - that traps fingers."),
 dict(n=10, title="Build the guards",
      groups=["Loft / Guards"], objects=[],
      tools="miter saw, spacer block, 2-1/2 inch screws",
      text=["Toe board flat on the deck first, then the top rail at 80 inches,",
            "then the balusters between them.",
            "Cut ONE spacer block and use it for every gap. Do not measure",
            "each one; you will drift.",
            "Gaps come out between 2-7/8 and 3 inches."],
      warn="Check every finished gap with a 3-1/2 inch block. Nothing passes."),
 dict(n=11, title="Hang the gate",
      groups=[], objects=["Gate "],
      tools="self-closing spring hinges, gate latch",
      extra=[(1, 'pair 3 inch self-closing spring hinges'), (1, 'gravity gate latch, black'), (1, 'magnetic catch')],
      text=["The gate leaf is built like a guard panel, 19-1/2 inches wide.",
            "Hinge it so it swings IN over the deck, never outward.",
            "Self-closing spring hinges, a gravity latch and a magnetic catch.",
            "No lock, no bolt, nothing a child can shut themselves behind."],
      warn="Let it go from wide open ten times. It must latch every time."),
 dict(n=12, title="Build the ladder — it lifts off",
      groups=["Ladder"], objects=[],
      tools="dado blade or router, 3/8 x 5 hitch pins",
      extra=[(2, '3/8" x 5" hitch pin with lanyard'), (1, '2x6 hanger rail (cut at step 4)')],
      text=["Two 2x4 stringers, five rungs at 7-5/16 inch risers.",
            "Dado each rung 3/4 inch into the stringers, then two screws per end.",
            "Notch the top of each stringer to hook over the 2x6 hanger rail.",
            "A 3/8 inch pin through each stringer locks it down.",
            "Rigid 2x2 grab rails on both sides. No rope."],
      warn="Pull two pins and the loft is unreachable. That is the toddler lock."),
 dict(n=13, title="Den shelf and the door itself",
      groups=["Loft / Den shelf"], objects=["Round hobbit door", "Strap hinge", "Door knob", "Door sill"],
      tools="strap hinges, 1/4 inch carriage bolts",
      extra=[(1, '27" circle, 3/4" ply - the door slab'), (2, '12" black strap hinge'), (1, '2-3/4" round wood knob'), (1, 'magnetic catch'), (1, 'door stop')],
      text=["Two low shelves inside the den for board books.",
            "The door slab is a 27 inch circle of 3/4 inch plywood, about 9 lb.",
            "Do not build it thicker. A toddler swings this.",
            "Through-bolt both strap hinges with carriage bolts. Screws sag.",
            "Add a doorstop so it cannot swing hard onto fingers."],
      warn="Magnetic catch only. It must push open from the inside."),
 dict(n=14, title="Sand, finish, and put the mat down",
      groups=[], objects=[],
      tools="150 and 180 grit, zero-VOC primer, mat",
      extra=[(1, '2 inch folding gym mat, 4 x 8 ft'), (1, 'qt zero-VOC primer'), (1, 'qt deep green eggshell'), (1, 'qt water-based satin topcoat')],
      text=["Sand every surface a child can grip to 180. Balusters, rails,",
            "rungs, grab rails, door edges, the whole den interior.",
            "Run a bare forearm over everything below 40 inches.",
            "Rough-sawn texture only where nobody touches it.",
            "Zero-VOC primer, then paint and topcoat.",
            "A 2 inch mat goes under the ladder and the open faces."],
      warn="3/4 inch foam is not enough for a 44 inch fall."),
]
